spring.application.name=JobApplicationTracker

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.vjgnzxjitmhfdombfdem
spring.datasource.password=sungmin123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

# GitHub Login
spring.security.oauth2.client.registration.github.client-id=Ov23liZXKN72Qhv0fMaB
spring.security.oauth2.client.registration.github.client-secret=7e5fc5b3e60ff0e5de6eeb65be6a41ec5de42d53

# Google Login


logging.level.org.springframework.security=DEBUG